#spring:
#  datasource:
#    url: jdbc:h2:mem:gearfirst
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug

server:
  # 정상 종료(Graceful Shutdown) 기능을 활성화합니다.
  shutdown: graceful
  servlet:
    # Ingress 경로와 맞추기 위한 전체 Prefix
    context-path: /parts

spring:
  lifecycle:
    # 각 종료 단계별 타임아웃을 30초로 설정하여, 로드밸런서가 연결을 해제할 시간을 충분히 줍니다.
    timeout-per-shutdown-phase: 30s

management:
  endpoint:
    health:
      probes:
        enabled: true