#spring:
#  datasource:
#    url: jdbc:h2:mem:gearfirst
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug

server:
  shutdown: graceful   # ✅ Spring Boot graceful shutdown 활성화
  servlet:
    context-path: /parts   # 서비스 Prefix (Ingress 경로와 동일하게)

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s  # ✅ shutdown 단계별 타임아웃
  datasource:
    # 프록시는 127.0.0.1 (localhost)로 DB 연결을 제공합니다.
    url: jdbc:postgresql://127.0.0.1:5432/partsdb
    username: postgres
    # 비밀번호는 아래 쿠버네티스 Secret에서 환경변수로 주입받습니다.
    password: ${DB_PASSWORD}

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,info