#spring:
#  datasource:
#    url: jdbc:h2:mem:gearfirst
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug

server:
  shutdown: graceful   # ✅ Spring Boot graceful shutdown 활성화
  servlet:
    context-path: /parts   # 서비스 Prefix (Ingress 경로와 동일하게)

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s  # ✅ shutdown 단계별 타임아웃
